### ISSUE TITLE
How to apply nginx SSL mode?

### ISSUE THREAD

**Issue by 6r6** [ryanmcdermott/docker-flask#1]
So sorry to bother you, Mr.ryanmcdermott !

I try to use ssl mode in nginx,and I add code to 'nginx.conf':

```
……
listen 443 ssl;
ssl_certificate /config/server.crt;
ssl_certificate_key /config/server.key;
……
```

server.crt and server.key is in /config/

this not work.
could you please reply the correct way of using SSL mode?

**Comment by ryanmcdermott** [comment]
I'm not entirely sure! Nginx has some docs that go into this more, that's all I got! I'm sorry 😢
